brew "ansible"
brew "awscli"
brew "bash"
brew "bat"
brew "bazaar"
brew "bfg"
brew "coreutils"
brew "curl"
brew "direnv"
brew "dep"
brew "dmd"
brew "fzf"
brew "ghq"
brew "gibo"
brew "git"
brew "glide"
brew "gnu-sed"
brew "goenv"
brew "hub"
brew "hugo"
brew "jq"
brew "jump"
brew "mercurial"
brew "mysql"
brew "openssl"
brew "peco"
brew "pt"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "shellcheck"
brew "travis"
brew "tfenv"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
tap "dpo/openblas", pin: true
brew "dpo/openblas/octave", args: ["devel", "with-qt", "with-java"]
brew "gnuplot", args: ["with-aquaterm"]

tap "caskroom/cask"
tap "caskroom/versions"
cask "alfred"
cask "appcleaner"
cask "boostnote"
cask "firefox"
cask "flux"
cask "fly"
cask "google-chrome"
cask "google-backup-and-sync"
cask "google-japanese-ime"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "kindle"
cask "marp"
cask "minikube"
cask "sequel-pro"
cask "spectacle"
cask "skype"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "virtualbox"
cask "aquaterm"
# comment out cask docker to fix old version docker
# cask docker

